### ISSUE TITLE
Hibernate logging

### ISSUE THREAD

**Issue by BaranovNikita** [liferay/portletmvc4spring#12]
Hello! I use your beautiful widget and hibernate in one. But I cant configure it for logging sql queries in liferay logs. May be you know how fix it? 

My Bean:
![image](https://user-images.githubusercontent.com/9808191/81727914-5925b180-9492-11ea-9cd2-d7e7b9ff2db2.png)

**Comment by ngriffin7a** [comment]
Hi @BaranovNikita Thanks for the kind words, and thanks for using PortletMVC4pring. I would recommend that you ask your question in the Liferay Forums or on Stackoverflow. Those are the places where you are most likely to get a helpful answer. Kind Regards, Neil

**Comment by ngriffin7a** [comment]
Closing this issue since it is does not seem to fall into the category of being a bug/defect in PortletMVC4Spring.
