### ISSUE TITLE
javax.annotation missing dependency?

### ISSUE THREAD

**Issue by fabian-bouche-liferay** [liferay/portletmvc4spring#16]
Hi!
I tried to build snapshot master branch but hit a missing javax.annotation package error on both demo modules.
Solved it by adding latest api to root's pom dependencyManagement :

```
    <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
        <version>1.3.2</version>
        <scope>provided</scope>
    </dependency>

```

And including it to both module's pom:

```
    <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
    </dependency>
```

Built using Liferay IDE + AWS Corretto JDK 11.0.8_10.

**Comment by fabian-bouche-liferay** [comment]
Switched to a JDK 8, then this api is not required at compilation time.

We should add this api to be compatible with JDK 11.

**Comment by ngriffin7a** [comment]
Fixed, see https://issues.liferay.com/browse/MVCS-47

**Comment by ngriffin7a** [comment]
@fabian-bouche-liferay Thanks for providing the fix!
