### ISSUE TITLE
Include Hibernate JPA to Spring MVC portlet

### ISSUE THREAD

**Issue by jjab2020** [liferay/portletmvc4spring#33]
Hello,

I hope that you are well.

Could you please help me to include Hibernate Core And JPA to This Spring MVC portlet.

I have tried to iclude Hibernate core dependency to build.gradle but it show me a lot of conflicts. could you please provide me a way to do it.
Many Thanks 

 Unresolved requirement: Import-Package: COM.newmonics.PercClassLoader; resolution:="optional"_  Unresolved requirement: Import-Package: android.os; resolution:="optional"_  Unresolved requirement: Import-Package: bsh; resolution:="optional"_  Unresolved requirement: Import-Package: com.caucho.hessian; resolution:="optional"_  Unresolved requirement: Import-Package: com.caucho.hessian.client; resolution:="optional"_  Unresolved requirement: Import-Package: com.caucho.hessian.io; resolution:="optional"_  Unresolved requirement: Import-Package: com.caucho.hessian.server; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.aalto; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.aalto.evt; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.aalto.stax; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.cbor; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.smile; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.xml; resolution:="optional"_  Unresolved requirement: Import-Package: com.github.luben.zstd; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.common.base; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.protobuf; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.protobuf.util; resolution:="optional"_  Unresolved requirement: Import-Package: com.googlecode.protobuf.format; resolution:="optional"_  Unresolved requirement: Import-Package: com.ibm.websphere.jtaextensions; resolution:="optional"_  Unresolved requirement: Import-Package: com.ibm.websphere.security; resolution:="optional"_  Unresolved requirement: Import-Package: com.ibm.wsspi.uow; resolution:="optional"_  Unresolved requirement: Import-Package: com.jamonapi; resolution:="optional"_  Unresolved requirement: Import-Package: com.jamonapi.utils; resolution:="optional"_  Unresolved requirement: Import-Package: com.jayway.jsonpath; resolution:="optional"_  Unresolved requirement: Import-Package: com.jayway.jsonpath.spi.mapper; resolution:="optional"_  Unresolved requirement: Import-Package: com.lowagie.text; resolution:="optional"_  Unresolved requirement: Import-Package: com.lowagie.text.pdf; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.core; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.core.dml; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.core.support; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.core.types; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.core.types.dsl; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.jpa; resolution:="optional"_  Unresolved requirement: Import-Package: com.querydsl.jpa.impl; resolution:="optional"_  Unresolved requirement: Import-Package: com.rometools.rome.feed.atom; resolution:="optional"_  Unresolved requirement: Import-Package: com.rometools.rome.feed.rss; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.jna; resolution:="optional"_  Unresolved requirement: Import-Package: com.sun.net.httpserver; resolution:="optional"_  Unresolved requirement: Import-Package: com.thoughtworks.paranamer; resolution:="optional"_  Unresolved requirement: Import-Package: freemarker.cache; resolution:="optional"_  Unresolved requirement: Import-Package: freemarker.core; resolution:="optional"_  Unresolved requirement: Import-Package: freemarker.ext.jsp; resolution:="optional"_  Unresolved requirement: Import-Package: freemarker.ext.servlet; resolution:="optional"_  Unresolved requirement: Import-Package: freemarker.template; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.lang; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.text; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.text.markup; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.transform; resolution:="optional"_  Unresolved requirement: Import-Package: groovy.xml; resolution:="optional"_  Unresolved requirement: Import-Package: io.reactivex; resolution:="optional"_  Unresolved requirement: Import-Package: io.reactivex.functions; resolution:="optional"_  Unresolved requirement: Import-Package: io.reactivex.rxjava3.core; resolution:="optional"_  Unresolved requirement: Import-Package: io.rsocket.plugins; resolution:="optional"_  Unresolved requirement: Import-Package: io.smallrye.mutiny; resolution:="optional"_  Unresolved requirement: Import-Package: io.smallrye.mutiny.groups; resolution:="optional"_  Unresolved requirement: Import-Package: io.undertow.connector; resolution:="optional"_  Unresolved requirement: Import-Package: io.undertow.server; resolution:="optional"_  Unresolved requirement: Import-Package: io.undertow.server.handlers; resolution:="optional"_  Unresolved requirement: Import-Package: io.undertow.util; resolution:="optional"_  Unresolved requirement: Import-Package: io.vavr; resolution:="optional"_  Unresolved requirement: Import-Package: io.vavr.collection; resolution:="optional"_  Unresolved requirement: Import-Package: io.vavr.control; resolution:="optional"_  Unresolved requirement: Import-Package: javafx.beans.property; resolution:="optional"_  Unresolved requirement: Import-Package: javafx.beans.value; resolution:="optional"_  Unresolved requirement: Import-Package: javax.annotation.meta; resolution:="optional"_  Unresolved requirement: Import-Package: javax.ejb; resolution:="optional"_  Unresolved requirement: Import-Package: javax.enterprise.concurrent; resolution:="optional"_  Unresolved requirement: Import-Package: javax.faces.application; resolution:="optional"_  Unresolved requirement: Import-Package: javax.faces.component; resolution:="optional"_  Unresolved requirement: Import-Package: javax.faces.context; resolution:="optional"_  Unresolved requirement: Import-Package: javax.faces.event; resolution:="optional"_  Unresolved requirement: Import-Package: javax.money; resolution:="optional"_  Unresolved requirement: Import-Package: javax.money.format; resolution:="optional"_  Unresolved requirement: Import-Package: javax.resource; resolution:="optional"_  Unresolved requirement: Import-Package: javax.resource.cci; resolution:="optional"_  Unresolved requirement: Import-Package: javax.resource.spi; resolution:="optional"_  Unresolved requirement: Import-Package: javax.resource.spi.endpoint; resolution:="optional"_  Unresolved requirement: Import-Package: javax.resource.spi.work; resolution:="optional"_  Unresolved requirement: Import-Package: javax.security.jacc; resolution:="optional"_  Unresolved requirement: Import-Package: jdk.internal.misc; resolution:="optional"_  Unresolved requirement: Import-Package: jdk.jfr; resolution:="optional"_  Unresolved requirement: Import-Package: joptsimple; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.collections; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.coroutines; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.coroutines.intrinsics; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.coroutines.jvm.internal; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.jvm; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.jvm.functions; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.jvm.internal; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.reflect; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.reflect.full; resolution:="optional"_  Unresolved requirement: Import-Package: kotlin.reflect.jvm; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.coroutines; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.coroutines.flow; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.coroutines.reactive; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.coroutines.reactor; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.serialization; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.serialization.descriptors; resolution:="optional"_  Unresolved requirement: Import-Package: kotlinx.serialization.json; resolution:="optional"_  Unresolved requirement: Import-Package: net.minidev.json; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.ehcache; resolution:="optional"_  Unresolved requirement: Import-Package: okhttp3; resolution:="optional"_  Unresolved requirement: Import-Package: okhttp3.internal.http; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.avalon.framework.logger; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.catalina.connector; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.commons.pool2; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.commons.pool2.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.coyote; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.derby.jdbc; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.client5.http.cookie; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.client5.http.impl.async; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.client5.http.impl.cookie; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.client5.http.protocol; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.concurrent; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.http; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.http.message; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.http.nio; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.http.nio.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.http.protocol; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.hc.core5.reactive; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.http.impl.nio.client; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.http.nio.client; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.http.nio.entity; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.log; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.hssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.ss.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.xssf.streaming; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.xssf.usermodel; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.access; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.definition; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.definition.dao; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.definition.digester; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.el; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.evaluator; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.evaluator.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.extras.complete; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.factory; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.impl.mgmt; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.locale; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.locale.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.preparer; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.preparer.factory; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.renderer; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.request; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.request.locale; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.request.render; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.request.servlet; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tiles.startup; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tomcat.util.buf; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tomcat.util.http; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant.taskdefs; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant.types; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.bridge; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.ast; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.bcel; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.internal.tools; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.loadtime; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.patterns; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.reflect; resolution:="optional"_  Unresolved requirement: Import-Package: org.aspectj.weaver.tools; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.cms; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.pkcs; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.x500; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.x509; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cert; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cms; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cms.jcajce; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto.engines; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto.generators; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto.modes; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto.paddings; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.crypto.params; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.jce.provider; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.brotli.dec; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.control; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.control.customizers; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.reflection; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.runtime; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.runtime.callsite; resolution:="optional"_  Unresolved requirement: Import-Package: org.codehaus.groovy.runtime.typehandling; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.client; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.client.api; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.http; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.io; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.reactive.client; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.util.component; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.jetty.util.thread; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.persistence.jpa; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.persistence.queries; resolution:="optional"_  Unresolved requirement: Import-Package: org.eclipse.persistence.sessions; resolution:="optional"_  Unresolved requirement: Import-Package: org.glassfish.hk2.osgiresourcelocator; resolution:="optional"_  Unresolved requirement: Import-Package: org.jboss.logmanager; resolution:="optional"_  Unresolved requirement: Import-Package: org.joda.time; resolution:="optional"_  Unresolved requirement: Import-Package: org.joda.time.format; resolution:="optional"_  Unresolved requirement: Import-Package: org.objectweb.jonas_tm; resolution:="optional"_  Unresolved requirement: Import-Package: org.openid4java.consumer; resolution:="optional"_  Unresolved requirement: Import-Package: org.opensaml.core; resolution:="optional"_  Unresolved requirement: Import-Package: org.reactivestreams; resolution:="optional"_  Unresolved requirement: Import-Package: org.slf4j.impl; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.asm.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.beans.factory.aspectj; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.hateoas; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.hateoas.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.hateoas.server.core; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.hateoas.server.mvc; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.instrument; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.ldap.core; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.ldap.core.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.handler.invocation; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.rsocket; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.rsocket.annotation.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.simp; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.simp.annotation.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.simp.config; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.messaging.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.oxm; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.ldap; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.ldap.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.ldap.search; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.ldap.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.ldap.userdetails; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.access.expression; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.access.intercept; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.context; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.util.matcher; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.web.csrf; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.messaging.web.socket.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.endpoint; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.oidc.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.oidc.userinfo; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.registration; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.userinfo; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.web; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.web.method.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.web.reactive.result.method.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.web.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.client.web.server.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.core; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.core.endpoint; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.core.oidc.user; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.core.user; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.jwt; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.introspection; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.web; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.web.access; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.web.access.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.oauth2.server.resource.web.server; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.openid; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.rsocket.api; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.rsocket.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.rsocket.authorization; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.rsocket.core; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.rsocket.util.matcher; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.saml2.provider.service.authentication; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.saml2.provider.service.registration; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.saml2.provider.service.servlet.filter; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.security.saml2.provider.service.web; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.ui.freemarker; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.reactive; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.reactive.config; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.reactive.result.method; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.reactive.result.method.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.reactive.result.view; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.socket.config.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.socket.server.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.socket.sockjs; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.socket.sockjs.support; resolution:="optional"_  Unresolved requirement: Import-Package: org.springframework.web.socket.sockjs.transport; resolution:="optional"_  Unresolved requirement: Import-Package: org.synchronoss.cloud.nio.multipart; resolution:="optional"_  Unresolved requirement: Import-Package: org.synchronoss.cloud.nio.stream.storage; resolution:="optional"_  Unresolved requirement: Import-Package: org.threeten.bp; resolution:="optional"_  Unresolved requirement: Import-Package: org.tukaani.xz; resolution:="optional"_  Unresolved requirement: Import-Package: org.webjars; resolution:="optional"_  Unresolved requirement: Import-Package: org.xmlbeam; resolution:="optional"_  Unresolved requirement: Import-Package: org.xmlbeam.config; resolution:="optional"_  Unresolved requirement: Import-Package: org.xmlbeam.io; resolution:="optional"_  Unresolved requirement: Import-Package: org.xnio; resolution:="optional"_  Unresolved requirement: Import-Package: org.xnio.channels; resolution:="optional"_  Unresolved requirement: Import-Package: org.yaml.snakeyaml; resolution:="optional"_  Unresolved requirement: Import-Package: org.yaml.snakeyaml.constructor; resolution:="optional"_  Unresolved requirement: Import-Package: org.yaml.snakeyaml.reader; resolution:="optional"_  Unresolved requirement: Import-Package: org.yaml.snakeyaml.representer; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.blockhound; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.blockhound.integration; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.core; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.core.publisher; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.core.scheduler; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty.http; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty.http.client; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty.http.server; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty.resources; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.netty.transport; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.util.context; resolution:="optional"_  Unresolved requirement: Import-Package: reactor.util.function; resolution:="optional"_  Unresolved requirement: Import-Package: rx; resolution:="optional"_  Unresolved requirement: Import-Package: rx.functions; resolution:="optional"_  Unresolved requirement: Import-Package: scala; resolution:="optional"_  Unresolved requirement: Import-Package: scala.runtime; resolution:="optional"_  Unresolved requirement: Import-Package: sun.nio.ch; resolution:="optional"_  Unresolved requirement: Import-Package: sun.reflect; resolution:="optional"_  Unresolved requirement: Import-Package: sun.security.util; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.service; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.servlet.jsp.compiler; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.spring.context; resolution:="optional"_  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9))"_ [Sanitized]

Have a great day

**Comment by ngriffin7a** [comment]
Assuming that you generated your PortletMVC4Spring portlet using the `mvn archetype:generate ...` command listed here:
https://github.com/liferay/portletmvc4spring#archetypes

Also assuming that you added the dependencies for Hibernate Core And JPA to the build.gradle file of the generated project.

Whenever you get a list of "Unresolved requirement" errors, you need to solve the one at the END of the list first.

In your case, this needs to be solved:
```
Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=9))"_ 
```

This implies that you compiled your WAR artifact with JDK 9, but are running Liferay with a JRE that is not 9. The version that you compile with should match the version you are running with. At this point, I would recommend that you compile with JDK 11, and run with JRE 11.

**Comment by jjab2020** [comment]
Hello thanks for the reply but I'm using jdk 8 for the both the portlet and liferay portal very strange

**Comment by ngriffin7a** [comment]
It might be the case that one of the Hibernate or JPA jars was compiled with JDK 9. If that's the case, then you need to run Liferay with the highest Java version. Since 8 will not work for you, 11 is the next Long Term Support (LTS) release from Oracle, so I'd recommend 11.

**Comment by jjab2020** [comment]
Hello I would like really to thank you for the help many thanks for all yours useful informations, I will try with jdk 11 .

Have a good day

**Comment by ngriffin7a** [comment]
@jjab2020 It was my pleasure to help. Thanks for using PortletMVC4Spring! :-)
