### ISSUE TITLE
SessionStatus set to complete on every render and resource phase

### ISSUE THREAD

**Issue by XenoGearX** [liferay/portletmvc4spring#4]
In the PortletRequestMappingHandlerAdapter class line 1037 - 1040 the SessionStatus is always set to complete for every render and resource phase.
Because of this everything that has been added with the @SessionAttributes annotation is removed and not available during an action phase which follows a render or resource phase.
Is this behaviour intentional or is this a bug?

**Comment by ngriffin7a** [comment]
@XenoGearX Thank you for asking this question. I spent some time just now researching the answer but I'll need more time. I hope to get back to you soon. Thanks in advance for your patience. Kind Regards, Neil

**Comment by XenoGearX** [comment]
@ngriffin7a Thanks for taking time to research it. I posted the same question on the Liferay forum with more details and a use case which we have: https://liferay.dev/forums/-/message_boards/message/118728033
Regards, Safet

**Comment by ngriffin7a** [comment]
@XenoGearX Thanks again for reporting this issue. Please "watch" [MVCS-37](https://issues.liferay.com/browse/MVCS-37) in JIRA for future updates.

**Comment by XenoGearX** [comment]
@ngriffin7a Thanks for the update

**Comment by ngriffin7a** [comment]
@XenoGearX After consulting my schedule, I should be able to spend time on this on Thursday of this week (April 16, 2020).

Note that my commit caused a JUnit test failure, and so I will have to make a follow-up commit in order to fix that.

**Comment by ngriffin7a** [comment]
@XenoGearX As I recently mentioned in https://github.com/liferay/portletmvc4spring/issues/5, I fixed the JUnit failure with commit https://github.com/liferay/portletmvc4spring/commit/9ebfc74041a49039acf65f835d96446355987075 which qualifies as the follow-up commit I promised to make in the earlier comment.

I'll be closing this GitHub issue now. If you have any questions, please comment on https://issues.liferay.com/browse/MVCS-37 in JIRA.

Thanks for using PortletMVC4Spring! :)
