### ISSUE TITLE
ModelAndView not created correctly

### ISSUE THREAD

**Issue by Condor70** [liferay/portletmvc4spring#6]
I just migrated from spring-webmvc-portlet to portletmvc4spring 5.2.0 an ran into the following regression:

The following code generates a ModelAndView wrapped inside the model of another ModelAndView without a view:

```
@RequestMapping
public ModelAndView render(ModelMap model) {
  model.put("data", ...);
  return new ModelAndView("viewName", model);
}
```

This results in the following error:

```
javax.portlet.PortletException: ModelAndView [ModelAndView: materialized View is [null]; model is {data: ..., modelAndView=ModelAndView: reference to view with name 'viewName'; model is {data: ...}, org.springframework.validation.BindingResult.data=org.springframework.validation.BeanPropertyBindingResult: 0 errors, org.springframework.validation.BindingResult.modelAndView=org.springframework.validation.BeanPropertyBindingResult: 0 errors}] neither contains a view name nor a View object in portlet with name 'portletName'
```

As stated, this used to work in spring-webmvc-portlet!

I temporarily worked around this problem by rewriting the method to:
```
@RequestMapping
public String render(ModelMap model) {
  model.put("data", ...);
  return "viewName";
}
```

**Comment by ngriffin7a** [comment]
@Condor70 Thanks for reporting this issue. I'll investigate as soon as I can and get back to you with my findings. Thanks in advance for your patience. Kind Regards, Neil

**Comment by ngriffin7a** [comment]
@Condor70 I haven't forgotten about this issue. Hope to get to it this week. Thanks for your patience. -- Neil

**Comment by ngriffin7a** [comment]
@Condor70 After consulting my schedule, I should be able to spend time on this on Thursday of this week (April 16, 2020).

**Comment by ngriffin7a** [comment]
@Condor70 Thanks for reporting this issue. I just fixed it in commit https://github.com/liferay/portletmvc4spring/commit/c5b16e1a60e0b12c9a4128dda997518221f44950 as part of the following issue:
https://issues.liferay.com/browse/MVCS-38

The fix now resides in the following branches:

https://github.com/liferay/portletmvc4spring/tree/master (currently at version 5.2.1-SNAPSHOT, compatible with Spring Framework 5.2.x)

https://github.com/liferay/portletmvc4spring/tree/5.1.x (currently at version 5.1.2-SNAPSHOT, compatible with Spring Framework 5.1.x)

In order for you to try the fix in your environment, please do the following:

    git clone https://github.com/liferay/portletmvc4spring.git

    git checkout 5.1.x # ONLY IF YOU NEED TO WORK WITH Spring Framework 5.1.x

    mvn clean install

Then, update the pom.xml descriptors in your Maven pom.xml descriptors to use version 5.2.1-SNAPSHOT or 5.1.2-SNAPSHOT of the PortletMVC4Spring dependencies.

Finally, rebuild your portlet WAR modules with:

    mvn clean package

After you deploy the rebuild WAR modules to $LIFERAY_HOME/deploy, please give them a try and let me know if the fix works.

**Comment by ngriffin7a** [comment]
@Condor70 I'll be closing this GitHub issue now. Please feel free to comment on (or reopen) https://issues.liferay.com/browse/MVCS-38 if this is still a problem in your environment.

Thanks,

Neil
