### ISSUE TITLE
Action that doens't modify response throws IllegalStateException

### ISSUE THREAD

**Issue by Condor70** [liferay/portletmvc4spring#7]
An action mapping that doesn't modify the response returns a ModelAndView instead of null, which causes an IllegalStateException exception (Invalid action method return value).

```
@ActionMapping
public void action(ModelMap model) {
	model.put("data", ...);
}
```

If I modify the code slightly it does work correctly:
```
@ActionMapping
public void action(ModelMap model, ActionResponse response) {
	model.put("data", ...);
	response.getRenderParameters().setValue("done", "true");
}
```

**Comment by Condor70** [comment]
An action mapping that doesn't modify the response returns a ModelAndView instead of null, which causes an IllegalStateException exception (Invalid action method return value).

```
@ActionMapping
public void action(ModelMap model) {
	model.put("data", ...);
}
```

If I modify the code slightly it does work correctly:
```
@ActionMapping
public void action(ModelMap model, ActionResponse response) {
	model.put("data", ...);
	response.getRenderParameters().setValue("done", "true");
}
```

**Comment by ngriffin7a** [comment]
@Condor70 Thanks for reporting this issue as well. I'll report back after I have an opportunity to investigate. Kind Regards, Neil

**Comment by ngriffin7a** [comment]
@Condor70 I haven't forgotten about this issue. Hope to get to it this week. Thanks for your patience. -- Neil

**Comment by ngriffin7a** [comment]
@Condor70 After consulting my schedule, I should be able to spend time on this on Thursday of this week (April 16, 2020).

**Comment by ngriffin7a** [comment]
@Condor70 I'm pretty sure that this steps from the same issue that you reported in https://github.com/liferay/portletmvc4spring/issues/6.

I'll be closing this GitHub issue, but feel free to comment on https://issues.liferay.com/browse/MVCS-38 if you still find this to be a problem.

Thanks, Neil

**Comment by Condor70** [comment]
Can you reopen this issue?

MVCS-38 has solved issue #6, but not this one.

**Comment by ngriffin7a** [comment]
@Condor70 Re-opening as you asked. I think I just fixed the problem in https://issues.liferay.com/browse/MVCS-42. Please build PortletMVC4Spring 5.2.1-SNAPSHOT (the current master branch) from source and try it in your project. If all is well then we can close this GitHub issue and perform the release, hopefully quite soon.

**Comment by Condor70** [comment]
Thanks! Your commit has indeed fixed the problem.

**Comment by ngriffin7a** [comment]
@Condor70 Thanks for confirming that the commit fixed the problem. I'll close this GitHub issue. Hope to make a 5.2.1 release in the coming days or weeks.
